name: CI Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar tests
        run: npm test